name: Lint

on:
  push:

jobs:
  install-dependencies:
    uses: ./.github/workflows/install-dependencies.yml

  install-pnpm:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2

  run-lint:
    name: Run linters
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - run: pnpm run format
      - run: pnpm run lint
